### ISSUE TITLE
Add mcc "0000"

### ISSUE THREAD

**Issue by MatheusRod0296** [DannielWhatever/emvqr#3]
Hi man, 

I found a issue  in MCC , that list dont have  a code "0000"  as  https://www.mreports.com/documentation/emr/mcc_codes.htm

Here there a example about a QrCode  like mcc "0000" , 

00020126400014BR.GOV.BCB.PIX0118teste@teste.com.br5204**0000**5303986540550.005802BR5909Test name6009Sao Paulo62110507Payment63049C98

I tested a scenery with the mcc below and dont had problems
{
    "mcc": "0000",
    "edited_description": "No Mcc",
    "combined_description": "No Mcc",
    "usda_description": "No Mcc",
    "irs_description": "No Mcc",
    "irs_reportable": "",
    "id": 981
  }
  
  I dont know all impacts about this change, but i leave here my suggestion :)

**Comment by DannielWhatever** [comment]
Hi, sorry for not answering before, i have not be able to be active in Github these months, but I appreciate your feedback and i have taken it into consideration.

I just publish a new version **emvqr@1.0.0-alpha.0** , and I added the specification for "No Mcc" just as you suggested. Also, the decoder is now tolerant to unknown specifications in the scope of MCC, countries and currencies.
 
Have a great weekend :)
